### ISSUE TITLE
Exception in org.iets3.core.expr.natlang.constraints.NatLangFunctionArgRef_Constraints

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#21]
```
java.lang.IllegalArgumentException: fromIndex(1) > toIndex(0)
    at java.util.SubList.<init>(AbstractList.java:624)
    at java.util.AbstractList.subList(AbstractList.java:484)
    at jetbrains.mps.internal.collections.runtime.ListSequence.tailListSequence(ListSequence.java:38)
    at org.iets3.core.expr.natlang.constraints.NatLangFunctionArgRef_Constraints$1$1.createSearchScopeOrListOfNodes(Unknown Source)
    at jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider.createSearchScope(BaseReferenceScopeProvider.java:39)
    at jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider.createScope(BaseReferenceScopeProvider.java:59)
    at jetbrains.mps.smodel.constraints.ReferenceDescriptor$OkReferenceDescriptor.getScope(ReferenceDescriptor.java:131)
    at jetbrains.mps.smodel.action.ChildSubstituteActionsHelper.createSmartReferenceActions(ChildSubstituteActionsHelper.java:245)
    at jetbrains.mps.smodel.action.ChildSubstituteActionsHelper.createDefaultSubstituteActions(ChildSubstituteActionsHelper.java:205)
    at jetbrains.mps.smodel.action.ChildSubstituteActionsHelper.createPrimaryChildSubstituteActions(ChildSubstituteActionsHelper.java:185)
    at jetbrains.mps.smodel.action.ChildSubstituteActionsHelper.createActions_internal(ChildSubstituteActionsHelper.java:121)
    at jetbrains.mps.smodel.action.ChildSubstituteActionsHelper.createActions(ChildSubstituteActionsHelper.java:60)
    at jetbrains.mps.smodel.action.ModelActions.createChildNodeSubstituteActions(ModelActions.java:32)
    at jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo.createActions(DefaultChildSubstituteInfo.java:95)
    at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.getActions(AbstractNodeSubstituteInfo.java:179)
    at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.getActionsFromCache(AbstractNodeSubstituteInfo.java:220)
    at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.access$000(AbstractNodeSubstituteInfo.java:48)
    at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo$2.compute(AbstractNodeSubstituteInfo.java:158)
    at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo$2.compute(AbstractNodeSubstituteInfo.java:155)
    at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
    at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:97)
    at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
    at jetbrains.mps.smodel.ModelAccessHelper.runReadAction(ModelAccessHelper.java:44)
    at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.getMatchingActions(AbstractNodeSubstituteInfo.java:155)
    at de.slisson.mps.richtext.runtime.WordCellSubstituteInfo.getMatchingActions(WordCellSubstituteInfo.java:38)
    at jetbrains.mps.nodeEditor.EditorComponent$30.lambda$compute$0(EditorComponent.java:2545)
    at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.doExecute(TypeContextManager.java:273)
    at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.execute(TypeContextManager.java:246)
    at jetbrains.mps.typesystem.inference.TypeContextManager.runTypeCheckingComputation(TypeContextManager.java:120)
    at jetbrains.mps.nodeEditor.EditorComponent$30.compute(EditorComponent.java:2543)
    at jetbrains.mps.nodeEditor.EditorComponent$30.compute(EditorComponent.java:2539)
    at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
    at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:97)
    at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
    at jetbrains.mps.nodeEditor.EditorComponent.runRead(EditorComponent.java:2451)
    at jetbrains.mps.nodeEditor.EditorComponent.getMatchingActions(EditorComponent.java:2539)
    at jetbrains.mps.nodeEditor.EditorComponent.activateNodeSubstituteChooser(EditorComponent.java:2513)
    at jetbrains.mps.nodeEditor.EditorComponent.activateNodeSubstituteChooser(EditorComponent.java:2483)
    at jetbrains.mps.nodeEditor.NodeEditorActions$Complete.execute(NodeEditorActions.java:689)
    at jetbrains.mps.nodeEditor.actions.ActionHandlerImpl$1.doExecute(ActionHandlerImpl.java:56)
    at jetbrains.mps.editor.runtime.commands.EditorCommand.run(EditorCommand.java:54)
    at jetbrains.mps.smodel.WorkbenchModelAccess$CommandRunnable$1.run(WorkbenchModelAccess.java:632)
    at jetbrains.mps.smodel.WriteActionDispatcher.run(WriteActionDispatcher.java:39)
    at jetbrains.mps.smodel.WorkbenchModelAccess$3.run(WorkbenchModelAccess.java:136)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:145)
    at jetbrains.mps.smodel.WorkbenchModelAccess$CommandRunnable.run(WorkbenchModelAccess.java:627)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
    at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteActionInCommand(WorkbenchModelAccess.java:440)
    at jetbrains.mps.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:403)
    at jetbrains.mps.project.ProjectModelAccess.executeCommand(ProjectModelAccess.java:43)
    at jetbrains.mps.nodeEditor.actions.ActionHandlerImpl.executeAction(ActionHandlerImpl.java:53)
    at jetbrains.mps.nodeEditor.actions.ActionHandlerImpl.executeAction(ActionHandlerImpl.java:43)
    at jetbrains.mps.nodeEditor.selection.EditorCellSelection.executeAction(EditorCellSelection.java:166)
    at jetbrains.mps.nodeEditor.selection.EditorCellLabelSelection.executeAction(EditorCellLabelSelection.java:172)
    at jetbrains.mps.ide.editor.actions.Complete_Action.doExecute(Complete_Action.java:59)
    at jetbrains.mps.workbench.action.BaseAction$2.run(BaseAction.java:145)
    at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:155)
    at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
    at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
    at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
    at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:587)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$132(IdeKeyEventDispatcher.java:634)
    at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:633)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:477)
    at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:609)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:387)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by wsafonov** [comment]
fixed in commit ff20f67
