### ISSUE TITLE
InfHelper.div(..., precision, ...) should call BigDecimal#divide() with a rounding mode

### ISSUE THREAD

**Issue by sergej-koscejev** [IETS3/iets3.opensource#7]
Otherwise the following exception occurs:
```
java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
	at java.math.BigDecimal.divide(BigDecimal.java:1690)
	at java.math.BigDecimal.divide(BigDecimal.java:1723)
	at org.iets3.core.expr.simpleTypes.plugin.InfHelper.div(InfHelper.java:82)
	at org.iets3.core.expr.simpleTypes.typesystem.TypesystemDescriptor$CustomOverloadedOperationsTypesProvider_d.getOperationType(TypesystemDescriptor.java:248)
	at jetbrains.mps.lang.typesystem.runtime.OverloadedOperationsManager.getOperationType(OverloadedOperationsManager.java:86)
	...
```
and the type of d1 / d2 is not computed properly in NumerTypeCalculation test.

**Comment by markusvoelter** [comment]
I fixed it, but we still need to revisit the exact semantics of the numerical operations, taking into account rounding and precision. I am currently not familiar enough with BigDecimal.
